### ISSUE TITLE
APIM [2.1] [2.0] - Product Profile Documentation Improvements

### ISSUE THREAD

**Issue by ruwiniwj** [wso2/docs-apim#1466]
**Description:**
Noticed the following issues in the documentation [1] and [2].

**Publisher/Store/Key Manager**

The doc for 2.1 only gives instruction to comment WS Transport Sender from axis2.xml and remove WebSocketInboundEndpoint. Also, the same step is duplicated twice. However, we need to need to comment both WS and WSS TransportSenders and remove both WebSocketInboundEndpoint and SecuredWebSocketInboundEndpoint. 

In 2.0, we do not have WS or WSS Transport Senders or relevant inbound endpoints, so we can remove those notes from [2]

**Publisher/Store**

In both 2.1 and 2.0 Store, Publisher profiles, when BlockConditions config is enabled, the following exception is thrown in server startup.
```
Unexpected character (<) at position 27.
at org.json.simple.parser.Yylex.yylex(Unknown Source)
at org.json.simple.parser.JSONParser.nextToken(Unknown Source)
at org.json.simple.parser.JSONParser.parse(Uranknown Source)
at org.json.simple.parser.JSONParser.parse(Unknown Source)
at org.json.simple.parser.JSONParser.parse(Unknown Source)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData_aroundBody2(KeyTemplateRetriever.java:101)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.retrieveKeyTemplateData(KeyTemplateRetriever.java:64)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService_aroundBody6(KeyTemplateRetriever.java:117)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.loadKeyTemplatesFromWebService(KeyTemplateRetriever.java:116)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run_aroundBody0(KeyTemplateRetriever.java:55)
at org.wso2.carbon.apimgt.gateway.throttling.util.KeyTemplateRetriever.run(KeyTemplateRetriever.java:51)
at java.util.TimerThread.mainLoop(Timer.java:555)
```
Block Conditions are not needed to be enabled in Store/Publisher. Hence we need to add a step to disable <BlockCondition> config in api-manager.xml of Store, Publisher.

**Traffic Manager**

The Traffic Manager profile is using axis2_TM.xml and registry_TM.xml as the axis2 and registry XML files. So we need to add instructions to remove the default axis2.xml and registry.xml and rename axis2_TM.xml and registry_TM.xml as axis2.xml and registry.xml

**Gateway Worker**

In 2.1 doc, We need to remove the argument "-DworkerNode=true" for starting the GatewayWorker profile. As we no longer use the gateway manager profile in 2.1, we can remove that from the profile table and from the table containing webapp information of each profile.

In both 2.0 and 2.1, we need to uncomment the <JMSEventPublisherParameters> config from api-manager.xml as we are not publishing blacklisting conditions from the gateway.

[1] https://docs.wso2.com/display/AM210/Product+Profiles#ProductProfiles-API-MProfiles
[2]. https://docs.wso2.com/display/AM200/Product+Profiles#ProductProfiles-API-MProfiles

**Comment by samgnaniah** [comment]
We will not be fixing this as this issue is based on an older version of the product.
