### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by zhucj1028** [wso2/docs-apim#5625]
Location : https://apim.docs.wso2.com/en/4.0.0/use-cases/streaming-tutorials/performing-real-time-etl-with-mysql/

How to solve such a problem, there is no documentation.

[2022-04-13_09-40-46_626] ERROR {io.debezium.connector.mysql.BinlogReader} - Encountered change event 'Event{header=EventHeaderV4{timestamp=1649814013000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=41, nextPosition=14003, flags=0}, data=TableMapEventData{tableId=17633, database='localtest_ei', table='test', columnTypes=15, 15, columnMetadata=765, 765, columnNullability={0, 1}, eventMetadata=null}}' at offset {ts_sec=1649814013, file=mysql-bin.000001, pos=13863, server_id=1, event=1} for table localtest_ei.test whose schema isn't known to this connector. One possible cause is an incomplete database history topic. Take a new snapshot in this case.
Use the mysqlbinlog tool to view the problematic event: mysqlbinlog --start-position=13943 --stop-position=14003 --verbose mysql-bin.000001 (Encoded) 
[2022-04-13_09-40-46_627] ERROR {io.debezium.connector.mysql.BinlogReader} - Error during binlog processing. Last offset stored = null, binlog reader near position = mysql-bin.000001/13943 
[2022-04-13_09-40-46_627] ERROR {io.debezium.connector.mysql.BinlogReader} - Failed due to error: Error processing binlog event 
org.apache.kafka.connect.errors.ConnectException: Encountered change event for table localtest_ei.test whose schema isn't known to this connector
	at io.debezium.connector.mysql.AbstractReader.wrap(AbstractReader.java:241)
	at io.debezium.connector.mysql.AbstractReader.failed(AbstractReader.java:218)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:607)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1100)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:951)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:594)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:838)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.ConnectException: Encountered change event for table localtest_ei.test whose schema isn't known to this connector
	at io.debezium.connector.mysql.BinlogReader.informAboutUnknownTableIfRequired(BinlogReader.java:875)
	at io.debezium.connector.mysql.BinlogReader.handleUpdateTableMetadata(BinlogReader.java:849)
	at io.debezium.connector.mysql.BinlogReader.handleEvent(BinlogReader.java:590)
	... 5 more

**Comment by Mariangela** [comment]
@zhucj1028 , it may be good if you can join us via WSO2's official Slack channels for better communication. 
You can talk to our developers directly regarding issues or concerns about the products.

[wso2-apim.slack.com](https://wso2-apim.slack.com/) : [Join](https://join.slack.com/t/wso2-apim/shared_invite/enQtNzEzMzk5Njc5MzM0LTgwODI3NmQ1MjI0ZDQyMGNmZGI4ZjdkZmI1ZWZmMjNkY2E0NmY3ZmExYjkxYThjNzNkOTU2NWJmYzM4YzZiOWU?src=sidebar)

**Comment by Mariangela** [comment]
@senthuran16 , please provide feedback in this regard.

**Comment by senthuran16** [comment]
@lasanthaS would be the best person to answer this. @lasanthaS FYI.

**Comment by dnwick** [comment]
@zhucj1028 Can you share the steps you tried please. Siddhi apps and datasource configuration

**Comment by rmsamitha** [comment]
Closing as no response is received from the reporter since a long time. Please reopen if needed further.
