### ISSUE TITLE
[Doc] Add instructions to disable token exchange grant type for IS as KM

### ISSUE THREAD

**Issue by Lakith-Rambukkanage** [wso2/docs-apim#6642]
## Problem 
Token exchange grant type is enabled by default in the APIM 4.1.0 and onwards using the following config.

```
[oauth.grant_type.token_exchange]
enable = true
allow_refresh_tokens = true
iat_validity_period = "1h"
```

IS does not support the token exchange grant type. 

When using IS as Key Manager it causes the following error when trying to generate keys with this grant type
Also both automated tryout key generation and key generation wizard have this grant type selected by default.

```
[2023-01-31 12:25:44,774] [6907c008-0a72-4ce6-8e49-7d92e5851f02] ERROR {org.wso2.is.key.manager.operations.endpoint.impl.DcrApiServiceImpl} - Internal Server Error org.wso2.carbon.identity.oauth.dcr.exception.DCRMServerException: Error occurred while creating application with application name:  admin_c1cec03e-ddb1-4005-b203-808c13daec5f_SANDBOX
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at org.wso2.carbon.identity.base.IdentityException.error(IdentityException.java:100)
    at org.wso2.carbon.identity.oauth.dcr.util.DCRMUtils.generateServerException(DCRMUtils.java:123)
    at org.wso2.is.key.manager.operations.endpoint.dcr.service.DCRMService.createOAuthApp(DCRMService.java:574)
    at org.wso2.is.key.manager.operations.endpoint.dcr.service.DCRMService.createOAuthApplication(DCRMService.java:417)
    at org.wso2.is.key.manager.operations.endpoint.dcr.service.DCRMService.registerApplication(DCRMService.java:91)
    at org.wso2.is.key.manager.operations.endpoint.impl.DcrApiServiceImpl.registerApplication(DcrApiServiceImpl.java:117)
```

```
Caused by: org.wso2.carbon.identity.oauth.IdentityOAuthClientException: 'urn:ietf:params:oauth:grant-type:token-exchange' grant type is not allowed.
    at org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl.handleClientError(OAuthAdminServiceImpl.java:353)
    at org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl.validateGrantTypes(OAuthAdminServiceImpl.java:346)
    at org.wso2.carbon.identity.oauth.OAuthAdminServiceImpl.registerAndRetrieveOAuthApplicationData(OAuthAdminServiceImpl.java:267)
    at org.wso2.carbon.identity.oauth.OAuthAdminService.registerAndRetrieveOAuthApplicationData(OAuthAdminService.java:133)
    at org.wso2.is.key.manager.operations.endpoint.dcr.service.DCRMService.createOAuthApp(DCRMService.java:572)
    ... 64 more
```

## Approach

Request the user to disable the token exchange grant type if and until it is supported by IS.

```
[oauth.grant_type.token_exchange]
enable = false
allow_refresh_tokens = true
iat_validity_period = "1h"
```

**Comment by chamilaadhi** [comment]
Add an entry to https://apim.docs.wso2.com/en/4.2.0/install-and-setup/setup/distributed-deployment/configuring-wso2-identity-server-as-a-key-manager/#step-4-configure-wso2-is-with-wso2-api-m

**Comment by RusJaI** [comment]
PR : https://github.com/wso2/docs-apim/pull/6798
The PR was merged. Hence closing this.
