### ISSUE TITLE
Fix mkdocs build command in the README

### ISSUE THREAD

**Issue by ruthryi** [wso2/docs-apim#6740]
In later versions of Python3, while trying to build mkdocs, we see the following error

```
wso2@mariangela en % mkdocs serve --dirtyreload 
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 14, in <module>
    from mkdocs import config
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/defaults.py", line 4, in <module>
    from mkdocs.config import config_options
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 5, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/usr/local/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/collections/__init__.py)
```

**Comment by ruthryi** [comment]
Fixed with https://github.com/wso2/docs-apim/pull/6739
