### ISSUE TITLE
Versions page not working due to a Jenkins build failure

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/docs-apim#7773]
**Description:**

Build [#10103](https://wso2.org/jenkins/job/docs/view/All/job/docs-apim/10103/console) is failing and throws the following error:

```
+ mkdocs build -c
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/jenkins/workspace/docs/docs-apim/en/site
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.10/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mkdocs/commands/build.py", line 320, in build
    _build_theme_template(template, env, files, config, nav)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mkdocs/commands/build.py", line 118, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/mkdocs/commands/build.py", line 97, in _build_template
    output = template.render(context)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/material/404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/material/main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/material/base.html", line 192, in top-level template code
    {% block footer %}
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/material/base.html", line 193, in block 'footer'
    {% include "partials/footer.html" %}
  File "/home/jenkins/workspace/docs/docs-apim/en/theme/material/partials/footer.html", line 74, in top-level template code
    {% block social %}
  File "/home/jenkins/workspace/docs/docs-apim/en/theme/material/partials/footer.html", line 75, in block 'social'
    {% include "partials/social.html" %}
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/material/partials/social.html", line 16, in top-level template code
    {% include ".icons/" ~ social.icon ~ ".svg" %}
  File "/root/.pyenv/versions/3.8.10/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/.svg
Build step 'Execute shell' marked build as failure

Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE
```

**Comment by DinithiDiaz** [comment]
Could locally build the page successfully by updating `footer.html` and `header.html` with the latest changes. Need to do the customizations specific to the documentation.

**Comment by dulithsenanayake** [comment]
Hi all,

Closing this since the issue was resolved by PR https://github.com/wso2/docs-apim/pull/7775

Thanks!
Dulith
