### ISSUE TITLE
Doc Feedback: API Manager Dont Load API/Publish/apis ... redirect API/carbon

### ISSUE THREAD

**Issue by MACT119** [wso2/docs-apim#8769]
Location : https://apim.docs.wso2.com/en/4.1.0/

 [2024-11-08 06:29:00,137] ERROR - [/authenticationendpoint] Exception sending context initialized event to listener instance of class [org.wso2.carbon.identity.mgt.endpoint.util.listener.IdentityManagementEndpointContextListener]
213java.lang.NoClassDefFoundError: org/apache/cxf/jaxrs/provider/json/JSONProvider
 
Caused by: java.lang.ClassNotFoundException: org.apache.cxf.jaxrs.provider.json.JSONProvider cannot be found by org.wso2.carbon.identity.mgt.endpoint.util_5.17.5
292	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:512) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
293	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:423) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
294	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:415) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
295	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:155) ~[org.eclipse.osgi_3.14.0.v20190517-1309.jar:?]
296	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
297	... 77 more

**Comment by nandika** [comment]
Can you provide more details on how to reproduce this issue.

Nandika
